In [1]:
from __future__ import print_function
import torch

In [2]:
torch.rand(5, 3)

tensor([[0.7798, 0.8254, 0.2296],
        [0.2826, 0.0832, 0.9978],
        [0.6331, 0.6986, 0.9205],
        [0.1845, 0.4474, 0.5913],
        [0.6891, 0.5189, 0.7397]])

In [3]:
torch.cuda.is_available()

False

In [4]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [5]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00,  2.0000e+00, -1.0473e+16],
        [ 8.5920e+09,  8.3010e+20,  6.5645e-07],
        [ 1.6987e-07,  2.6222e-09,  2.6657e-09],
        [ 2.7302e-06,  1.0478e+21,  8.3193e+20],
        [ 5.4069e+22,  1.6706e-07,  1.3662e-05]])


In [6]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7471, 0.6155, 0.4898],
        [0.6697, 0.8597, 0.8715],
        [0.5240, 0.9600, 0.1760],
        [0.0960, 0.4061, 0.8458],
        [0.6852, 0.0216, 0.6105]])


In [7]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
y = torch.Tensor([5.5, 3])
print(y)

tensor([5.5000, 3.0000])


In [9]:
help(y.new_ones)

Help on built-in function new_ones:

new_ones(...) method of torch.Tensor instance
    new_ones(size, dtype=None, device=None, requires_grad=False) -> Tensor
    
    Returns a Tensor of size :attr:`size` filled with ``1``.
    By default, the returned Tensor has the same :class:`torch.dtype` and
    :class:`torch.device` as this tensor.
    
    Args:
        size (int...): a list, tuple, or :class:`torch.Size` of integers defining the
            shape of the output tensor.
        dtype (:class:`torch.dtype`, optional): the desired type of returned tensor.
            Default: if None, same :class:`torch.dtype` as this tensor.
        device (:class:`torch.device`, optional): the desired device of returned tensor.
            Default: if None, same :class:`torch.device` as this tensor.
        requires_grad (bool, optional): If autograd should record operations on the
            returned tensor. Default: ``False``.
    
    Example::
    
        >>> tensor = torch.tensor((), dtype

In [10]:
y = y.new_ones(2, 3)
print(y)

y = torch.randn_like(y)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[-1.4702, -1.1374, -0.0528],
        [ 0.4071, -0.6169, -0.5122]])


In [11]:
print(y.size(), type(y.size()))

torch.Size([2, 3]) <class 'torch.Size'>


In [12]:
a = torch.rand(5, 3)
b = torch.rand(5, 3)
print(a + b)
print(torch.add(a, b))
result = torch.zeros(5, 3)
torch.add(a, b, out=result)
print(result)
print(a.add(b))
a.add_(b)
print(a)

tensor([[1.4580, 1.2961, 0.9369],
        [0.7556, 1.1605, 1.0017],
        [1.0055, 0.8776, 0.6962],
        [1.2281, 0.6913, 1.5164],
        [1.1936, 1.3845, 0.9791]])
tensor([[1.4580, 1.2961, 0.9369],
        [0.7556, 1.1605, 1.0017],
        [1.0055, 0.8776, 0.6962],
        [1.2281, 0.6913, 1.5164],
        [1.1936, 1.3845, 0.9791]])
tensor([[1.4580, 1.2961, 0.9369],
        [0.7556, 1.1605, 1.0017],
        [1.0055, 0.8776, 0.6962],
        [1.2281, 0.6913, 1.5164],
        [1.1936, 1.3845, 0.9791]])
tensor([[1.4580, 1.2961, 0.9369],
        [0.7556, 1.1605, 1.0017],
        [1.0055, 0.8776, 0.6962],
        [1.2281, 0.6913, 1.5164],
        [1.1936, 1.3845, 0.9791]])
tensor([[1.4580, 1.2961, 0.9369],
        [0.7556, 1.1605, 1.0017],
        [1.0055, 0.8776, 0.6962],
        [1.2281, 0.6913, 1.5164],
        [1.1936, 1.3845, 0.9791]])


In [13]:
print(a.t())
a.t_()
print(a)

tensor([[1.4580, 0.7556, 1.0055, 1.2281, 1.1936],
        [1.2961, 1.1605, 0.8776, 0.6913, 1.3845],
        [0.9369, 1.0017, 0.6962, 1.5164, 0.9791]])
tensor([[1.4580, 0.7556, 1.0055, 1.2281, 1.1936],
        [1.2961, 1.1605, 0.8776, 0.6913, 1.3845],
        [0.9369, 1.0017, 0.6962, 1.5164, 0.9791]])


In [14]:
print(a[:, 1])

tensor([0.7556, 1.1605, 1.0017])


In [15]:
n = torch.rand(6, 5)
z = n.view(-1, 3, 2)
print(z.size())
print(z)

torch.Size([5, 3, 2])
tensor([[[2.1894e-01, 5.3525e-01],
         [8.6677e-04, 6.5730e-01],
         [4.3887e-01, 8.1343e-01]],

        [[2.5103e-01, 9.9317e-01],
         [2.0912e-01, 9.5247e-01],
         [7.8771e-01, 9.7262e-01]],

        [[9.4948e-01, 8.3575e-02],
         [2.5195e-01, 3.3660e-01],
         [5.9188e-02, 9.9413e-01]],

        [[1.7886e-01, 4.9601e-01],
         [7.5714e-01, 8.0132e-01],
         [8.6870e-01, 6.1628e-01]],

        [[8.3832e-01, 4.4233e-01],
         [5.6719e-01, 5.6240e-02],
         [2.6860e-01, 8.8908e-01]]])


In [16]:
torch.tensor([1]).item()

1

In [17]:
var = torch.ones(10)
print(var)
var_np = var.numpy()
var.add_(1)
print(var_np)
var_v = torch.from_numpy(var_np)
print(var_v)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])


In [18]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

In [19]:
from torch import autograd

In [26]:
x = torch.rand(4, 4, requires_grad=True)
print(x.grad_fn)
y = x + 2
print(y)
print(y.grad_fn)
z = y.mean()
print(z)
z.backward()
print(x.grad)

None
tensor([[2.7767, 2.9418, 2.2108, 2.0291],
        [2.5506, 2.2312, 2.9159, 2.9253],
        [2.6722, 2.2005, 2.4090, 2.1929],
        [2.6374, 2.0301, 2.4046, 2.1152]], grad_fn=<AddBackward0>)
tensor(2.4527, grad_fn=<MeanBackward1>)
tensor([[0.0625, 0.0625, 0.0625, 0.0625],
        [0.0625, 0.0625, 0.0625, 0.0625],
        [0.0625, 0.0625, 0.0625, 0.0625],
        [0.0625, 0.0625, 0.0625, 0.0625]])


In [25]:
torch.tensor()

tensor([2, 2])

In [40]:
x = torch.randn(3, requires_grad=True)
y = x * 2
while  y.data.norm() < 2000:
    y = y * 2
print(y)
v = torch.tensor([1, 1, 1], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([ 566.9905, 2328.5261, -503.1274], grad_fn=<MulBackward0>)
tensor([1024., 1024., 1024.])


In [46]:
x = torch.randn(3)
print(x)
x = x.unsqueeze(0)
print(x)

tensor([-0.0972,  0.9189, -1.5379])
tensor([[-0.0972,  0.9189, -1.5379]])


In [62]:
m = torch.randint(2, (10,))
print(m)
n = torch.randint(2, (10,))
print(n)
print((m == n).sum().item())

tensor([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])
tensor([0, 1, 0, 0, 0, 1, 0, 1, 0, 1])
9


In [41]:
from torch import nn
from torch.nn import functional as F

In [ ]:
class Encoder(nn.Module):
    def __init__(self):
        self.gru = nn.GRU(256, 256,  4)
        self.attn = nn.
        
    
    def forward(self, x):
        x = nn.ReLU(self.gru(x)) 